# This is a config for E2B sandbox template.
# You can use template ID (akc5kc1yjddgr8j0g5vz) or template name (aura-nextjs-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("aura-nextjs-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("aura-nextjs-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('aura-nextjs-test-2')

team_id = "fbf8ee41-79c0-4caa-ac8b-1e1ee57f768a"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "aura-nextjs-test-2"
template_id = "akc5kc1yjddgr8j0g5vz"
